IBA_swiep/urls.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017 Haiko Eitzen and Nico Epp
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from __future__ import unicode_literals
"""IBA_swiep URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import patterns, include, url
from django.contrib import admin
from swiep import views


urlpatterns = patterns('',
    url(r'^$',
        views.map_view,
        name='map'
        ),
    url(r'^login/$',
        views.login_view,
        name='login'
        ),
    url(r'^logout/$',
        views.logout_view,
        name='logout'
        ),
    url(r'^home/$',
        views.home,
        name='home'
        ),
    url(r'^management/$',
        views.management,
        name='management'
        ),
    url(r'^churches/$',
        views.church_list,
        name='church_list'
        ),
    url(r'^churches/create/$',
        views.church_create,
        name='church_create'
        ),
    url(r'^churches/(?P<church_id>\d+)/$',
        views.church_read,
        name='church_read'
        ),
    url(r'^churches/(?P<church_id>\d+)/update/$',
        views.church_update,
        name='church_update'
        ),
    url(r'^churches/(?P<church_id>\d+)/delete/$',
        views.church_delete,
        name='church_delete'
        ),
    url(r'^churches/(?P<church_id>\d+)/ministry/create/$',
        views.churchleader_create_at_church,
        name='churchleader_create_at_church'
        ),
    url(r'^churches/(?P<church_id>\d+)/ministry/(?P<churchleader_id>\d+)/$',
        views.churchleader_read_at_church,
        name='churchleader_read_at_church'
        ),
    url(r'^churches/(?P<church_id>\d+)/ministry/(?P<churchleader_id>\d+)/update/$',
        views.churchleader_update_at_church,
        name='churchleader_update_at_church'
        ),
    url(r'^churches/(?P<church_id>\d+)/ministry/(?P<churchleader_id>\d+)/delete/$',
        views.churchleader_delete_at_church,
        name='churchleader_delete_at_church'
        ),
    url(r'^leaders/$',
        views.leader_list,
        name='leader_list'
        ),
    url(r'^leaders/create/$',
        views.leader_create,
        name='leader_create'
        ),
    url(r'^leaders/(?P<leader_id>\d+)/$',
        views.leader_read,
        name='leader_read'
        ),
    url(r'^leaders/(?P<leader_id>\d+)/update/$',
        views.leader_update,
        name='leader_update'
        ),
    url(r'^leaders/(?P<leader_id>\d+)/delete/$',
        views.leader_delete,
        name='leader_delete'
        ),
    url(r'^leaders/(?P<leader_id>\d+)/ministry/create/$',
        views.churchleader_create_at_leader,
        name='churchleader_create_at_leader'
        ),
    url(r'^leaders/(?P<leader_id>\d+)/ministry/(?P<churchleader_id>\d+)/$',
        views.churchleader_read_at_leader,
        name='churchleader_read_at_leader'
        ),
    url(r'^leaders/(?P<leader_id>\d+)/ministry/(?P<churchleader_id>\d+)/update/$',
        views.churchleader_update_at_leader,
        name='churchleader_update_at_leader'
        ),
    url(r'^leaders/(?P<leader_id>\d+)/ministry/(?P<churchleader_id>\d+)/delete/$',
        views.churchleader_delete_at_leader,
        name='churchleader_delete_at_leader'
        ),
    url(r'^conferences/$',
        views.conference_list,
        name='conference_list'
        ),
    url(r'^conferences/create/$',
        views.conference_create,
        name='conference_create'
        ),
    url(r'^conferences/(?P<conference_id>\d+)/$',
        views.conference_read,
        name='conference_read'
        ),
    url(r'^conferences/(?P<conference_id>\d+)/update/$',
        views.conference_update,
        name='conference_update'
        ),
    url(r'^conferences/(?P<conference_id>\d+)/delete/$',
        views.conference_delete,
        name='conference_delete'
        ),
   url(r'^users/$',
       views.user_list,
       name='user_list'
       ),
   url(r'^users/create/$',
       views.user_create,
       name='user_create'
       ),
   url(r'^users/(?P<user_id>\d+)/$',
       views.user_read,
       name='user_read'
       ),
   url(r'^users/(?P<user_id>\d+)/update/$',
       views.user_update,
       name='user_update'
       ),
   url(r'^users/(?P<user_id>\d+)/update/password/$',
       views.change_password,
       name='change_password'
       ),
   url(r'^users/(?P<user_id>\d+)/delete/$',
       views.user_delete,
       name='user_delete'
       ),
   url(r'^groups/$',
       views.group_list,
       name='group_list'
       ),
   url(r'^groups/create/$',
       views.group_create,
       name='group_create'
       ),
   url(r'^groups/(?P<group_id>\d+)/$',
       views.group_read,
       name='group_read'
       ),
   url(r'^groups/(?P<group_id>\d+)/update/$',
       views.group_update,
       name='group_update'
       ),
   url(r'^groups/(?P<group_id>\d+)/delete/$',
       views.group_delete,
       name='group_delete'
       ),
   url(r'^others/$',
       views.other_list,
       name='other_list'
       ),
   url(r'^others/denominations/create/$',
       views.denomination_create,
       name='denomination_create'
       ),
   url(r'^others/denominations/(?P<denomination_id>\d+)/delete/$',
       views.denomination_delete,
       name='denomination_delete'
       ),
   url(r'^others/languages/create/$',
       views.language_create,
       name='language_create'
       ),
   url(r'^others/languages/(?P<language_id>\d+)/delete/$',
       views.language_delete,
       name='language_delete'
       ),
)

swiep/models.py
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017 Haiko Eitzen and Nico Epp
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from __future__ import unicode_literals

from django.conf import settings
from django.core.exceptions import ValidationError, FieldError
from django.db import models
from django_countries.fields import CountryField
from djgeojson.fields import PointField
import datetime


class Church(models.Model):
    """
    This model represents the Church entity, the centerpiece of
    this system's data.

    A Church can be associated to Leaders and a Conference.
    """
    name = models.CharField("nombre", max_length=100, default='', error_messages={
        'blank': 'El nombre no puede quedar vacío',
    })
    denomination = models.ForeignKey(
        'Denomination', verbose_name="denominación",
        null=True, blank=True, on_delete=models.SET_NULL)
    conference = models.ForeignKey(
        'Conference', verbose_name="convención",
        null=True, blank=True, on_delete=models.SET_NULL,
        related_name='churches')
    language = models.ForeignKey(
        'Language', verbose_name="idioma",
        null=True, blank=True, on_delete=models.SET_NULL)
    phone_number = models.CharField("teléfono", max_length=50, blank=True, default='')
    email = models.EmailField(blank=True, default='', error_messages={
        'invalid': 'El formato del email no es válido',
    })
    web_site = models.CharField("sitio web", max_length=100, blank=True, default='')
    DPTO_CHOICES = [('Alto Paraguay', 'Alto Paraguay'),
                    ('Alto Paraná', 'Alto Paraná'),
                    ('Amambay', 'Amambay'),
                    ('Asunción', 'Asunción'),
                    ('Boquerón', 'Boquerón'),
                    ('Caaguazú', 'Caaguazú'),
                    ('Caazapá', 'Caazapá'),
                    ('Canindeyú', 'Canindeyú'),
                    ('Central', 'Central'),
                    ('Concepción', 'Concepción'),
                    ('Cordillera', 'Cordillera'),
                    ('Guairá', 'Guairá'),
                    ('Itapúa', 'Itapúa'),
                    ('Misiones', 'Misiones'),
                    ('Ñeembucú', 'Ñeembucú'),
                    ('Paraguarí', 'Paraguarí'),
                    ('Presidente Hayes', 'Presidente Hayes'),
                    ('San Pedro', 'San Pedro')]
    department = models.CharField("departamento", max_length=100, choices=DPTO_CHOICES, default='Asunción',
                                  error_messages={'blank': 'El departamento no puede quedar vacío',})
    city = models.CharField("ciudad", max_length=100, blank=True, default='')
    address = models.CharField("dirección", max_length=100, blank=True, default='')
    map_location = PointField("ubicación en el mapa", blank=True, default='')
    YEAR_CHOICES = []
    for r in range(1870, (datetime.datetime.now().year+1)):
        YEAR_CHOICES.append((r, r))
    foundation_year = models.IntegerField("año de fundación", choices=YEAR_CHOICES,
                                          default=datetime.datetime.now().year)
    membership = models.IntegerField("membresía", default=0)
    assistance = models.IntegerField("asistencia", default=0)
    owns_lot = models.BooleanField("posee terreno", default=False)
    owns_building = models.BooleanField("posee edificio", default=False)
    mother_church = models.ForeignKey(
        'self', verbose_name="iglesia madre",
        null=True, blank=True, on_delete=models.SET_NULL,
        related_name='daughter_churches')
    observation = models.CharField("observación", max_length=1000, blank=True, default='')
    # row_insert_time = models.DateTimeField(auto_now_add=True)
    # row_update_time = models.DateTimeField(auto_now=True)
    # row_insert_user = models.ForeignKey(User, related_name='created_clients')
    # row_update_user = models.ForeignKey(User, related_name='modified_clients')

    class Meta:
        verbose_name = 'iglesia'
        verbose_name_plural = 'iglesias'

    def __unicode__(self):
        return self.name


class Leader(models.Model):
    """
    A Leader is any person associated with a church ministry.

    An instance of Leader may be associated to zero, one or more Churches
    and a Church may associate zero, one or more Leaders.
    """
    first_names = models.CharField("nombre(s)", max_length=100, default='', error_messages={
        'blank': 'Nombre(s) no puede quedar vacío',
    })
    last_names = models.CharField("apellido(s)", max_length=100, default='', error_messages={
        'blank': 'Apellido(s) no puede quedar vacío',
    })
    member_of = models.ForeignKey(
        Church, verbose_name="miembro de",
        null=True, blank=True, on_delete=models.SET_NULL)
    birthdate = models.DateField("fecha de nacimiento", null=True, blank=True)
    nationality = CountryField("nacionalidad", null=True, blank=True)
    hometown = models.CharField("lugar de nacimiento", max_length=100, blank=True, default='')
    current_residence = models.CharField("residencia actual", max_length=100, blank=True, default='')
    phone_number = models.CharField("teléfono", max_length=50, blank=True, default='')
    email = models.EmailField(blank=True, default='', error_messages={
        'invalid': 'El formato del email no es válido',
    })
    EDUCATION_CHOICES = [('Primario', 'Primario'),
                         ('Secundario', 'Secundario'),
                         ('Universitario', 'Universitario'),
                         ('Ninguno', 'Ninguno')]
    maximum_education_level = models.CharField("nivel máximo de educación", max_length=50, choices=EDUCATION_CHOICES, default='Ninguno')
    theological_studies = models.CharField("formación teológica", max_length=100, blank=True, default='')
    profession = models.CharField("profesión", max_length=100, blank=True, default='')
    observation = models.CharField("observación", max_length=1000, blank=True, default='')

    class Meta:
        verbose_name = 'líder'
        verbose_name_plural = 'líderes'
        permissions = (("read_leader", "Can read Leader"),)

    @classmethod
    def all_as_choices(cls):
        yield (0, '---------')
        for leader in cls.objects.all():
            yield (leader.pk, '{} {}'.format(leader.first_names, leader.last_names))

    def __unicode__(self):
        return "{} {}".format(self.first_names, self.last_names)


class Conference(models.Model):
    """
    A Conference is a formally defined association of Churches.
    """
    name = models.CharField("nombre", max_length=100, default='', error_messages={
        'blank': 'El nombre no puede quedar vacío',
    })
    acronym = models.CharField("acrónimo", max_length=50, default='', error_messages={
        'blank': 'El acrónimo no puede quedar vacío',
    })
    denomination = models.ForeignKey(
        'Denomination', verbose_name="denominación",
        null=True, blank=True, on_delete=models.SET_NULL)
    phone_number = models.CharField("teléfono", max_length=50, blank=True, default='')
    email = models.EmailField(blank=True, default='', error_messages={
        'invalid': 'El formato del email no es válido',
    })
    web_site = models.CharField("sitio web", max_length=100, blank=True, default='')
    DPTO_CHOICES = [('', ''),
                    ('Alto Paraguay', 'Alto Paraguay'),
                    ('Alto Paraná', 'Alto Paraná'),
                    ('Amambay', 'Amambay'),
                    ('Asunción', 'Asunción'),
                    ('Boquerón', 'Boquerón'),
                    ('Caaguazú', 'Caaguazú'),
                    ('Caazapá', 'Caazapá'),
                    ('Canindeyú', 'Canindeyú'),
                    ('Central', 'Central'),
                    ('Concepción', 'Concepción'),
                    ('Cordillera', 'Cordillera'),
                    ('Guairá', 'Guairá'),
                    ('Itapúa', 'Itapúa'),
                    ('Misiones', 'Misiones'),
                    ('Ñeembucú', 'Ñeembucú'),
                    ('Paraguarí', 'Paraguarí'),
                    ('Presidente Hayes', 'Presidente Hayes'),
                    ('San Pedro', 'San Pedro')]
    department = models.CharField("departamento", max_length=100, choices=DPTO_CHOICES, blank=True, default='')
    city = models.CharField("ciudad", max_length=100, blank=True, default='')
    address = models.CharField("dirección", max_length=100, blank=True, default='')
    YEAR_CHOICES = []
    for r in range(1870, (datetime.datetime.now().year+1)):
        YEAR_CHOICES.append((r, r))
    foundation_year = models.IntegerField("año de fundación", choices=YEAR_CHOICES,
                                          default=datetime.datetime.now().year)
    observation = models.CharField("observación", max_length=1000, blank=True, default='')
    # row_insert_time = models.DateTimeField(auto_now_add=True)
    # row_update_time = models.DateTimeField(auto_now=True)
    # row_insert_user = models.ForeignKey(User, related_name='created_clients')
    # row_update_user = models.ForeignKey(User, related_name='modified_clients')

    class Meta:
        verbose_name = 'convención'
        verbose_name_plural = 'convenciones'

    def __unicode__(self):
        return self.name


class ChurchLeader(models.Model):
    """
    Association of a Church with a Leader
    """
    church = models.ForeignKey(
        Church, verbose_name="iglesia",
        on_delete=models.CASCADE,
        related_name='leaders')  # Refactor to churchleaders? 2 refs in views.py & church_form.html
    leader = models.ForeignKey(
        Leader, verbose_name="líder",
        on_delete=models.CASCADE, related_name='churches')
    ministry = models.CharField("ministerio", max_length=1000, default='Pastor')

    class Meta:
        unique_together = ('church', 'leader', 'ministry',)

    def clean(self):

swiep/templates/leader_form.html
{% extends 'workspace.html' %}
{% load bootstrap_tags %}
{% load leaflet_tags %}
{# Maybe use http://stackoverflow.com/a/27239186 instead of django-forms-bootstrap #}
{# More ideas to tweak form with css: http://stackoverflow.com/a/18962481 #}
{# Put leaflet tags for map_location field: https://github.com/makinacorpus/django-leaflet#in-forms #}

{% block css %}
    {{ block.super }}
    {% leaflet_css plugins="forms" %}
{% endblock %}
{% block javascript %}
    {{ block.super }}
    {% leaflet_js plugins="forms" %}
{% endblock %}

        {% block workspace %}
            <div class="row">
                <div class="col-lg-8 col-md-10 col-xs-12">
                    {% if CRUD == 'R' %}
                    <form class="form-horizontal" action=".">
                    {% else %}
                    <form class="form-horizontal" action="." method="post" novalidate>
                    {% endif %}
                        {% csrf_token %}

                        {% if CRUD == 'U' and perms.swiep.change_leader %}
                        {{ form|as_bootstrap_horizontal }}
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button type="submit" class="btn btn-primary">Guardar cambios</button>
                                {% if perms.swiep.delete_leader %}
                                <a class="btn btn-danger" href="{% url 'leader_delete' id %}" role="button">
                                    Eliminar
                                </a>
                                {% endif %}
                                <a class="btn btn-default" href="{% url 'leader_read' id %}" role="button">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                        {% elif CRUD == 'C' and perms.swiep.add_leader %}
                        {{ form|as_bootstrap_horizontal }}
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                            {% if has_hidden_data %}
                                <button type="submit"
                                        name="from_pastor_save_btn"
                                        value="true"
                                        class="btn btn-primary">
                                    Agregar líder
                                </button>
                                <button type="submit"
                                        name="from_pastor_cancel_btn"
                                        value="true"
                                        class="btn btn-default">
                                    Cancelar
                                </button>
                            {% else %}
                                <button type="submit" class="btn btn-primary">Agregar líder</button>
                                <a class="btn btn-default" href="{% url 'leader_list' %}" role="button">
                                    Cancelar
                                </a>
                            {% endif %}
                            </div>
                        </div>
                        {% elif CRUD == 'R' and perms.swiep.read_leader %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Nombre</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">{{ leader }}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Miembro de</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">{% if leader.member_of %}{{ leader.member_of.name }}
                                                               {% else %}A confirmar {% endif %}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Fecha de nacimiento</label>
                            <div class="col-sm-4">
                                <p class="form-control-static">{% if leader.birthdate %}{{ leader.birthdate }}
                                                               {% else %}A confirmar {% endif %}</p>
                            </div>
                            <label class="col-sm-2 control-label">Nacionalidad</label>
                            <div class="col-sm-4">
                                <p class="form-control-static">{% if leader.nationality %}{{ leader.nationality.name }}
                                                               {% else %}A confirmar {% endif %}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Lugar de nacimiento</label>
                            <div class="col-sm-4">
                                <p class="form-control-static">{% if leader.hometown != '' %}{{ leader.hometown }}
                                                               {% else %}A confirmar {% endif %}</p>
                            </div>
                            <label class="col-sm-2 control-label">Residencia actual</label>
                            <div class="col-sm-4">
                                <p class="form-control-static">{% if leader.current_residence != '' %}{{ leader.current_residence }}
                                                               {% else %}A confirmar {% endif %}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Teléfono</label>
                            <div class="col-sm-4">
                                <p class="form-control-static">{% if leader.phone_number != '' %}{{ leader.phone_number }}
                                                               {% else %}A confirmar {% endif %}</p>
                            </div>
                            <label class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-4">
                                <p class="form-control-static">{% if leader.email != '' %}{{ leader.email }}
                                                               {% else %}A confirmar {% endif %}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Nivel máximo de educación</label>
                            <div class="col-sm-4">
                                <p class="form-control-static">{% if leader.maximum_education_level != '' %}{{ leader.maximum_education_level }}
                                                               {% else %}A confirmar {% endif %}</p>
                            </div>
                            <label class="col-sm-2 control-label">Estudios teológicos</label>
                            <div class="col-sm-4">
                                <p class="form-control-static">{% if leader.theological_studies != '' %}{{ leader.theological_studies }}
                                                               {% else %}A confirmar {% endif %}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Profesión</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">{% if leader.profession != '' %}{{ leader.profession }}
                                                               {% else %}A confirmar {% endif %}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Observación</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">{% if leader.observation != '' %}{{ leader.observation }}
                                                               {% else %}Ninguna {% endif %}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                {% if perms.swiep.change_leader %}
                                <a href="{% url 'leader_update' id %}" class="btn btn-danger">Editar</a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <span class="panel-title">Ministerios</span>
                                {% if perms.swiep.add_churchleader %}
                                <a title="Agregar" class="btn btn-sm btn-primary pull-right"
                                   href="{% url 'churchleader_create_at_leader' id %}">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </a>
                                {% endif %}
                            </div>
                            <div class="table-responsive">
                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th><span class="pull-right">#</span></th>
                                            <th>Iglesia</th>
                                            <th>Cargo</th>
                                            <th colspan="3">Opciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for elem in leader.churches.all %}
                                        <tr>
                                            <td><span class="pull-right"><strong>{{ forloop.counter }}</strong></span></td>
                                            <td>
                                                <a href="{% url 'church_read' elem.church.pk %}">
                                                    {{ elem.church|truncatechars:50 }}</a>
                                            </td>
                                            <td>{{ elem.ministry|truncatechars:50 }}</td>
                                            <td style="width:40px">
                                                <a href="{% url 'churchleader_read_at_leader' id elem.pk %}">
                                                    <span title="Ver" class="glyphicon glyphicon-eye-open"></span>
                                                </a>
                                            </td>
                                            {% if perms.swiep.change_churchleader %}
                                            <td style="width:40px">
                                                <a href="{% url 'churchleader_update_at_leader' id elem.pk %}">
                                                    <span title="Modificar" class="glyphicon glyphicon-pencil"></span>
                                                </a>
                                            </td>
                                            {% endif %}
                                            {% if perms.swiep.delete_churchleader %}
                                            <td style="width:40px">
                                                <a href="{% url 'churchleader_delete_at_leader' id elem.pk %}">
                                                    <span title="Eliminar" class="glyphicon glyphicon-remove"></span>
                                                </a>
                                            </td>
                                            {% endif %}
                                        </tr>
                                    {% empty %}
                                        <tr>
                                            <td></td>
                                            <td><p>No hay ministerios para mostrar</p></td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        {% elif CRUD == 'D' and perms.swiep.delete_leader %}
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Nombre</label>
                            <div class="col-sm-10">
                                <p class="form-control-static">{{ leader }}</p>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-2">
                                <button type="submit" class="btn btn-danger">Confirmar eliminación</button>
                                <a class="btn btn-default" href="{% url 'leader_read' id %}" role="button">
                                    Cancelar
                                </a>
                            </div>
                        </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        {% endblock %}

swiep/templates/under_construction.html
{% extends "workspace.html" %}

        {% block title_breadcrumbs %}
            <h1>{{ page_title }}</h1>
            <ol class="breadcrumb">
            {% for b in breadcrumb %}
                <li><a title="{{ b.0 }}" href="{{ b.1 }}">{{ b.0|truncatechars:20 }}</a></li>
            {% endfor %}
                <li>{{ page_title }}</li>
            </ol>
        {% endblock %}

        {% block workspace %}
            <div class="row">
                <div class="col-sm-6 col-md-8">
                    <div class="row">
                    Página en construcción
                    </div>
                </div>
            </div>
        {% endblock %}